const imgData_2026 = {
  armor_king: {
    title: 'Armor King',
    imgs: {
      full: {
        src: require('./armor_king_2026_web.jpg'),
        width: 1125,
        height: 1500,
      },
      thumb: {
        src: require('./armor_king_2026_thumb.jpg'),
        width: 450,
        height: 600,
      },
    },
    year: '2026',
    description: 'Pen and watercolour on paper. 2026.',
    price: 0,
    original: 'SOLD',
    prints: 'NOTYET',
    printPrice: 0,
    buyUrl: '',
    ship: 'FREE_IRL',
    printUrl: '',
    discount: 0,
    discountPrint: 0,
    type: 'fantasy_watercolour_painting',
    story: '',
  },
  dacian_dragon_tattoo: {
    title: 'Dacian Dragon Tattoo',
    imgs: {
      full: {
        src: require('./dacian_dragon_tattoo_2026_web.jpg'),
        width: 1060,
        height: 1500,
      },
      thumb: {
        src: require('./dacian_dragon_tattoo_2026_thumb.jpg'),
        width: 424,
        height: 600,
      },
    },
    year: '2026',
    description: 'Pen and watercolour on paper. 2026.',
    price: 0,
    original: 'SOLD',
    prints: 'NOTYET',
    printPrice: 0,
    buyUrl: '',
    ship: 'FREE_IRL',
    printUrl: '',
    discount: 0,
    discountPrint: 0,
    type: 'fantasy_watercolour_painting',
    story: '',
  },
  girl_in_a_purple_dress: {
    title: 'Girl in a Purple Dress',
    imgs: {
      full: {
        src: require('./girl_in_a_purple_dress_2026_web.jpg'),
        width: 1200,
        height: 1500,
      },
      thumb: {
        src: require('./girl_in_a_purple_dress_2026_thumb.jpg'),
        width: 480,
        height: 600,
      },
    },
    year: '2026',
    description: 'Pen and watercolour on paper. 2026.',
    price: 0,
    original: 'SOLD',
    prints: 'NOTYET',
    printPrice: 0,
    buyUrl: '',
    ship: 'FREE_IRL',
    printUrl: '',
    discount: 0,
    discountPrint: 0,
    type: 'fantasy_watercolour_painting',
    story: '',
  },
  lorreh_soba_and_the_turtle: {
    title: 'Lorreh Soba and the Turtle',
    imgs: {
      full: {
        src: require('./lorreh_soba_and_the_turtle_2026_web.jpg'),
        width: 1061,
        height: 1500,
      },
      thumb: {
        src: require('./lorreh_soba_and_the_turtle_2026_thumb.jpg'),
        width: 424,
        height: 600,
      },
    },
    year: '2026',
    description: 'Pen and watercolour on paper. 2026.',
    price: 0,
    original: 'SOLD',
    prints: 'NOTYET',
    printPrice: 0,
    buyUrl: '',
    ship: 'FREE_IRL',
    printUrl: '',
    discount: 0,
    discountPrint: 0,
    type: 'fantasy_watercolour_painting',
    story: '',
  },
  the_changewing_nest: {
    title: 'The Changewing Nest',
    imgs: {
      full: {
        src: require('./the_changewing_nest_2026_web.jpg'),
        width: 1125,
        height: 1500,
      },
      thumb: {
        src: require('./the_changewing_nest_2026_thumb.jpg'),
        width: 450,
        height: 600,
      },
    },
    year: '2026',
    description: 'Pen and watercolour on paper. 2026.',
    price: 0,
    original: 'SOLD',
    prints: 'NOTYET',
    printPrice: 0,
    buyUrl: '',
    ship: 'FREE_IRL',
    printUrl: '',
    discount: 0,
    discountPrint: 0,
    type: 'fantasy_watercolour_painting',
    story: '',
  },
  the_dream_of_zarathustra: {
    title: 'The Dream of Zarathustra',
    imgs: {
      full: {
        src: require('./the_dream_of_zarathustra_2026_web.jpg'),
        width: 1125,
        height: 1500,
      },
      thumb: {
        src: require('./the_dream_of_zarathustra_2026_thumb.jpg'),
        width: 450,
        height: 600,
      },
    },
    year: '2026',
    description: 'Pen and watercolour on paper. 2026.',
    price: 0,
    original: 'SOLD',
    prints: 'NOTYET',
    printPrice: 0,
    buyUrl: '',
    ship: 'FREE_IRL',
    printUrl: '',
    discount: 0,
    discountPrint: 0,
    type: 'fantasy_watercolour_painting',
    story: '',
  },
};

export default imgData_2026;
